---
- name: Set up Magma Federated Gateway build environment on a local machine
  hosts: feg
  become: yes
  vars:
    magma_root: /home/{{ ansible_user }}/magma
    preburn: false
    full_provision: true

  roles:
    - role: gateway_dev
      vars:
        distribution: "xenial"
        config_dir: "feg/gateway/configs"
    - role: golang
      vars:
        user: "{{ ansible_user }}"
    - role: feg_dev
      vars:
        user: "{{ ansible_user }}"
        config_dir: "feg/gateway/configs"
    - role: feg_services
